# Generated by Django 4.0.5 on 2022-07-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(default='', max_length=100)),
                ('companyname', models.CharField(default='', max_length=100)),
                ('companylogo', models.ImageField(blank=True, default='', upload_to='store/images')),
                ('description', models.CharField(default='', max_length=500)),
                ('jobcategory', models.CharField(default='', max_length=50)),
                ('jobtype', models.CharField(default='', max_length=50)),
                ('joblevel', models.CharField(default='', max_length=50)),
                ('salaryfrom', models.IntegerField(blank=True, default='1')),
                ('salaryto', models.IntegerField(blank=True, default='1')),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(default='', max_length=500)),
                ('url', models.CharField(default='', max_length=150)),
                ('email', models.CharField(default='', max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('skills', models.CharField(default='', max_length=300)),
                ('location', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
