# Generated by Django 4.0.5 on 2022-07-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0002_postedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedjob',
            name='employerid',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
