# Generated by Django 4.0.5 on 2022-07-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0003_postedjob_employerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=150)),
                ('gender', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField(blank=True, default='1')),
                ('Headlines', models.CharField(default='', max_length=150)),
                ('Aboutcompany', models.CharField(default='', max_length=350)),
                ('joblocation', models.CharField(default='', max_length=150)),
                ('faceebook', models.CharField(default='', max_length=150)),
                ('twitter', models.CharField(default='', max_length=150)),
                ('googleplus', models.CharField(default='', max_length=150)),
                ('youtube', models.CharField(default='', max_length=150)),
                ('dof', models.DateField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=150)),
                ('gender', models.CharField(default='', max_length=50)),
                ('phone', models.BigIntegerField(default='1')),
                ('Headlines', models.CharField(default='', max_length=150)),
                ('Aboutcompany', models.CharField(default='', max_length=350)),
                ('joblocation', models.CharField(default='', max_length=150)),
                ('faceebook', models.CharField(default='', max_length=150)),
                ('twitter', models.CharField(default='', max_length=150)),
                ('googleplus', models.CharField(default='', max_length=150)),
                ('youtube', models.CharField(default='', max_length=150)),
                ('dof', models.DateField(max_length=8)),
            ],
        ),
    ]
