# Generated by Django 4.0.5 on 2022-07-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0006_jobsekerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsekerprofile',
            name='userid',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
