# Generated by Django 4.0.5 on 2022-07-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0007_jobsekerprofile_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(default='', max_length=100)),
                ('jobtype', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('companyname', models.CharField(default='', max_length=100)),
                ('flag', models.IntegerField(default='0')),
                ('fileupload', models.FileField(blank=True, default='', upload_to='store/pdfs')),
                ('employerid', models.CharField(default='0', max_length=50)),
                ('userid', models.CharField(default='0', max_length=50)),
            ],
        ),
    ]
