# Generated by Django 4.0.5 on 2022-07-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0009_appliedjobs_address_appliedjobs_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsekerprofile',
            name='contactnumber',
            field=models.BigIntegerField(blank=True, default='1'),
        ),
    ]
