# Generated by Django 4.0.5 on 2022-07-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0010_alter_jobsekerprofile_contactnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('typeofjob', models.CharField(default=True, max_length=50)),
                ('userid', models.CharField(default=True, max_length=50)),
                ('employerid', models.CharField(default='0', max_length=50)),
                ('empid', models.IntegerField(default='0')),
                ('jobsekerid', models.IntegerField(default='0')),
                ('companyname', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
