# Generated by Django 4.0.5 on 2022-07-14 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0012_savedjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedjobs',
            name='expirydate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
