# Generated by Django 4.0.5 on 2022-07-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0013_savedjobs_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedjobs',
            name='saveddate',
            field=models.DateTimeField(),
        ),
    ]
