# Generated by Django 4.0.5 on 2022-07-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0014_alter_savedjobs_saveddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedjobs',
            name='saveddate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
