# Generated by Django 4.0.5 on 2022-07-14 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0016_candidatesavedjobs_alter_savedjobs_saveddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesavedjobs',
            name='datesaved',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidatesavedjobs',
            name='salaryfrom',
            field=models.IntegerField(blank=True, default='1'),
        ),
        migrations.AddField(
            model_name='candidatesavedjobs',
            name='salaryto',
            field=models.IntegerField(blank=True, default='1'),
        ),
        migrations.AlterField(
            model_name='candidatesavedjobs',
            name='saveddate',
            field=models.DateField(default='0', max_length=8),
        ),
    ]
