# Generated by Django 4.0.5 on 2022-07-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0018_candidatesaved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedjob',
            name='description',
            field=models.TextField(),
        ),
    ]
