# Generated by Django 4.0.5 on 2022-08-04 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0020_postedjob_deleteflag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsekerprofile',
            name='experience',
        ),
    ]
