# Generated by Django 4.0.5 on 2022-08-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0023_jobsekerprofile_currentjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='currentjob',
            field=models.CharField(default='', max_length=150),
        ),
    ]
