# Generated by Django 4.0.5 on 2022-08-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0024_appliedjobs_currentjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedjobs',
            name='experience',
        ),
    ]
