# Generated by Django 4.0.5 on 2022-08-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0026_appliedjobs_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='deleteflag',
            field=models.IntegerField(default='0'),
        ),
    ]
