# Generated by Django 4.0.5 on 2022-08-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0027_appliedjobs_deleteflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=150)),
                ('phone', models.BigIntegerField(default='1')),
                ('companyname', models.CharField(default='', max_length=150)),
                ('employerid', models.CharField(default='0', max_length=50)),
            ],
        ),
    ]
