# Generated by Django 4.0.5 on 2022-08-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0028_employeecontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecontact',
            name='empaddress',
            field=models.TextField(default=''),
        ),
    ]
