# Generated by Django 4.0.5 on 2022-08-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0030_remove_jobsekerprofile_joblevel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsekerprofile',
            name='singaporean',
            field=models.CharField(default='', max_length=150),
        ),
    ]
