# Generated by Django 4.0.5 on 2022-08-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0032_postedjob_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postedjob',
            old_name='language',
            new_name='language1',
        ),
        migrations.AddField(
            model_name='postedjob',
            name='language2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='postedjob',
            name='language3',
            field=models.CharField(default='', max_length=500),
        ),
    ]
