# Generated by Django 4.0.5 on 2022-08-11 11:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0033_rename_language_postedjob_language1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedjob',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
