# Generated by Django 4.0.5 on 2022-08-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0034_alter_postedjob_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedjob',
            name='description',
            field=models.TextField(),
        ),
    ]
