# Generated by Django 4.0.5 on 2022-08-12 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0035_alter_postedjob_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
