# Generated by Django 4.0.5 on 2022-08-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0037_postedjob_joblinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactname', models.CharField(default='', max_length=100)),
                ('contactemail', models.CharField(default='', max_length=150)),
                ('contactphonenumber', models.BigIntegerField(default='1')),
                ('contactsubject', models.CharField(default='', max_length=150)),
                ('contactmessage', models.CharField(default='0', max_length=50)),
            ],
        ),
    ]
