# Generated by Django 4.0.5 on 2022-08-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0038_contactdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='contactmessage',
            field=models.TextField(),
        ),
    ]
