# Generated by Django 4.0.5 on 2022-08-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0039_alter_contactdetail_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedjob',
            name='date',
            field=models.DateField(),
        ),
    ]
