# Generated by Django 4.0.5 on 2022-08-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0040_alter_postedjob_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedjob',
            name='salaryfrom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='postedjob',
            name='salaryto',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
