# Generated by Django 4.0.5 on 2022-08-24 06:54

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('jobportal', '0041_alter_postedjob_salaryfrom_alter_postedjob_salaryto'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedjob',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
