# Generated by Django 4.0.5 on 2022-08-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0042_postedjob_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postedjob',
            old_name='joblevel',
            new_name='openings',
        ),
        migrations.RemoveField(
            model_name='postedjob',
            name='date',
        ),
        migrations.RemoveField(
            model_name='postedjob',
            name='language1',
        ),
        migrations.RemoveField(
            model_name='postedjob',
            name='language2',
        ),
        migrations.RemoveField(
            model_name='postedjob',
            name='language3',
        ),
        migrations.RemoveField(
            model_name='postedjob',
            name='url',
        ),
    ]
