# Generated by Django 4.0.5 on 2022-08-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0043_rename_joblevel_postedjob_openings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedjob',
            name='username',
            field=models.CharField(default='', max_length=300),
        ),
    ]
