# Generated by Django 4.0.5 on 2022-08-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0044_postedjob_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillsrequired', models.CharField(max_length=500)),
            ],
        ),
    ]
