# Generated by Django 4.0.5 on 2022-08-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0045_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedjob',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
