# Generated by Django 4.0.5 on 2022-10-03 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0048_alter_postedjob_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeContact',
            new_name='EmployerContact',
        ),
    ]
